baseURL = "http://carlosaya.github.io/"
canonifyURLs = true
languageCode = "en-us"
theme = "hugo-travelify-theme"
title = "Samford Kindergarten"
[Taxonomies]
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 12
[[menu.main]]
name = "Links"
url = "/links/"
weight = 11
[[menu.main]]
name = "Gallery"
url = "/gallery/"
weight = 10
[[menu.main]]
name = "FAQ"
url = "/faq/"
weight = 9
[[menu.main]]
name = "Enrol"
url = "/enrol/"
weight = 8
[[menu.main]]
name = "Fees"
url = "/fees/"
weight = 7
[[menu.main]]
name = "Program"
url = "/program/"
weight = 6
[[menu.main]]
name = "Facilities"
url = "/facilities/"
weight = 5
[[menu.main]]
name = "Staff"
url = "/staff/"
weight = 4
[[menu.main]]
name = "About"
url = "/about/"
weight = 3
[[menu.main]]
name = "Philosophy"
url = "/philosophy/"
weight = 2
[[menu.main]]
name = "Open Day"
url = "/openday/"
weight = 1
[[menu.main]]
name = "Home"
url = "/home/"
weight = 1
[params]
author = "Samford C&K"
avatar = "css/images/avatar.png"
copyright = "Copyright Samford Kindergarten"
custom_css = []
custom_js = []
date_format = "2006-01-02T00:00:00+00:00"
disable_mathjax = false
logo = "css/images/header.jpg"
[params.slider]
enable = true
num_features = 1
[social]
facebook = "SamfordCommunityKindergarten"
