baseurl = "https://carlosaya.github.io/SCK/"
defaultContentLanguage = "en"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-universal-theme"
themesDir = "./themes"
title = "Samford Kindergarten"
[Permalinks]
blog = "/blog/:year/:month/:day/:filename/"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.topbar]]
name = "SamfordKindergarten"
pre = "<i class='fa fa-2x fa-facebook'></i>"
url = "http://facebook.com/SamfordCommunityKindergarten"
weight = 1
[[menu.topbar]]
name = "Email"
pre = "<i class='fa fa-2x fa-envelope'></i>"
url = "mailto:admin@samfordkindergarten.com.au"
weight = 2
[params]
about_us = "<p>We believe that childhood is a unique time of life to be valued and enjoyed. Children develop their sense of belonging by celebrating the richness of the history of Samford Kindergarten and the connections the centre has with community past, present and future.</p>"
address = "<p><strong>Samford Community Kindergarten</strong>\n        <br>17 Camp Mountain Road\n        <br>Samford Village, Queensland\n        <br>4520<br><br>\n      </p>"
author = "Samford Community Kindergarten"
copyright = "Copyright (c) 2018, Samford Community Kindergarten; all rights reserved."
date_format = "2006-01-02T00:00:00+00:00"
defaultdescription = "Samford Community Kindergarten"
defaultkeywords = []
email = "admin@samfordkindergarten.com.au"
googlemapsapikey = "AIzaSyDRyBNMdqcHvIhp_gtEkBOwsU5oBKVg3Wg"
latitude = "-27.377481"
logo = "img/logo.png"
longitude = "152.888002"
style = "default"
viewmorepostlink = "./blog/"
[params.carousel]
enable = true
[params.clients]
enable = false
subtitle = ""
title = "Our Clients"
[params.features]
enable = false
[params.recent_posts]
enable = true
subtitle = "There's always something fun and interesting for your little ones to experience at Samford Community Kindergarten.  Please check back here regularly to see what's happening in and around the Kindy!"
title = "From our blog"
[params.see_more]
enable = true
icon = "fa fa-child"
link_text = "Tell Me More!"
link_url = "./enrol/index.html"
subtitle = "Your child may be placed on the waiting list from the 1st of July of the year following their birth. Children are enrolled at the Centre in order of placement on the waiting list. As waiting lists are usually long at Samford Kindy, we advise placing children’s names on the list as soon as possible."
title = "Enrol Now"
[params.testimonials]
enable = true
subtitle = "<table><tr><td style=\"padding: 15px; background-color: #ffffffdd;\"><div class=\"text\">Using the Queensland Kindergarten Guidelines as a basis for programming, children will engage in a stimulating, engaging, challenging and relevant program focusing on their individual needs and abilities.<br><br><img src=\"img/accreditation-890.png\"></div></td></tr></table>"
title = "Queensland Approved"
[params.topbar]
enable = false
text = "<p class=\"hidden-sm hidden-xs\"></p>\n      <p class=\"hidden-md hidden-lg\"><a href=\"#\" data-animate-hover=\"pulse\"><i class=\"fa fa-phone\"></i></a>\n      <a href=\"#\" data-animate-hover=\"pulse\"><i class=\"fa fa-envelope\"></i></a>\n      </p>\n      "
