---
label: default
hide_body: false
is_partial: false
fields:
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- type: file
  name: banner
  label: Banner image for the blog post
pages:
- content/devwl.md
- content/waiting-listv2.md
- content/program.md
- content/enrol.md
- content/facilities.md
